### ISSUE TITLE
Missing hash

### ISSUE THREAD

**Issue by ldez** [labbsr0x/goh#3]
Have you push forced on the master branch?

hashes seem to have disappeared:
- 94bcf1cb07b70b26b72ad54b2b050bcd0a66a9c8
- 8b16b4848295
- ...

**Comment by eabili0** [comment]
Hello @ldez, sorry but I had to rewrite all my commit's author email address (compliance issues). 

I did it thinking no one was using this repo. Sorry for the inconvenience.

**Comment by ldez** [comment]
It's the dependence of `github.com/labbsr0x/bindman-dns-webhook` which is used by [lego](https://github.com/go-acme/lego).
lego is used by a lot of projects.

You broke all projects that depend on it.

**Comment by eabili0** [comment]
Got it. I'll create a release for `goh` then and push a fix for lego's `go.mod`

**Comment by ldez** [comment]
I already fixed lego.

But now the problem spreads to projects dependent on lego.

**Comment by eabili0** [comment]
Like `Traefik`, for instance?

**Comment by ldez** [comment]
yes, like Traefik or Caddy.

https://github.com/ldez/traefik-certs-dumper/issues/43
https://github.com/ldez/traefik-certs-dumper/issues/44
https://github.com/ldez/traefik-certs-dumper/issues/45

**Comment by ldez** [comment]
if you create a tag, it will be great.

**Comment by eabili0** [comment]
Done: https://github.com/labbsr0x/goh/releases/tag/v1.0.0

**Comment by eabili0** [comment]
I think this is as far as my powers go to solve this issue. Lessons learned for all of us: we must avoid `go.mod` dependencies pinned by commit hashes. Rebases are normal and should not be blamed. Thanks @ldez, I'll be closing this issue for now.

**Comment by ldez** [comment]
Could you also add a `go.mod` file ?

The overview of the impact:
https://github.com/search?q=github.com%2Flabbsr0x%2Fgoh&type=Code

**Comment by eabili0** [comment]
Of course.

**Comment by eabili0** [comment]
Done, @ldez. Anything else?

**Comment by ldez** [comment]
no, thanks.
